name: Generate a build and push to another branch

on:
  push:
    branches:
      - main # The branch name your are commit the new changes

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: git-checkout
        uses: actions/checkout@v3

      - name: Install all dependencies
        run: npm install

      - name: Build
        run: npm run build # The build command of your project

      - name: Copy build output and push to build branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git clone --depth 1 --branch build https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} build_repo
          rsync -av --delete out/ build_repo/
          cd build_repo
          git add .
          git commit -m "Build: ${GITHUB_SHA}"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} build --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}